defmodule XMAVLink.Test.Tasks do
  use ExUnit.Case

  import ExUnit.CaptureIO
  import Mix.Tasks.Xmavlink

  @input "#{File.cwd!()}/test/input/test_mavlink.xml"
  @output_dir "#{Mix.Project.build_path()}/generated"
  @output "#{@output_dir}/test_mavlink.ex"
  @output_module "TestMavlink"

  setup do
    File.rm_rf!(@output_dir)
    File.mkdir_p!(@output_dir)

    :ok
  end

  test "generate" do
    output =
      capture_io(fn ->
        assert :ok = run([@input, @output, @output_module])
      end)

    assert output =~ "Generated #{@output_module}"
    assert File.exists?(@output)

    # We don't care if we redefine MAVLink modules while running the following test
    previous_compiler_options = Code.compiler_options()
    Code.compiler_options(ignore_module_conflict: true)

    on_exit(fn ->
      Code.compiler_options(previous_compiler_options)
    end)

    # Confirm the list of modules generated from common.xml and its includes
    pairs =
      Enum.zip(
        [
          XMAVLink.Message.TestMavlink.Message.ChangeOperatorControl,
          XMAVLink.Message.TestMavlink.Message.Data16,
          XMAVLink.Message.TestMavlink.Message.Heartbeat,
          XMAVLink.Message.TestMavlink.Message.VfrHud,
          TestMavlink,
          TestMavlink.Message.ChangeOperatorControl,
          TestMavlink.Message.Data16,
          TestMavlink.Message.Heartbeat,
          TestMavlink.Message.VfrHud,
          TestMavlink.Types
        ]
        |> Enum.sort(),
        Code.compile_file(@output)
        |> Keyword.keys()
        |> Enum.sort()
      )

    for {expected, actual} <- pairs do
      assert expected == actual
    end
  end

  test "generated output is deterministic and formatter-compatible" do
    output_a = Path.join(@output_dir, "deterministic_a.ex")
    output_b = Path.join(@output_dir, "deterministic_b.ex")

    capture_io(fn ->
      assert :ok = run([@input, output_a, @output_module])
      assert :ok = run([@input, output_b, @output_module])
    end)

    generated = File.read!(output_a)

    assert generated == File.read!(output_b)
    assert generated == formatted(generated)
    refute generated =~ @input
    assert generated =~ "generated by MAVLink mix task from test_mavlink.xml"
  end

  test "generate succeeds when output is already current" do
    output =
      capture_io(fn ->
        assert :ok = run([@input, @output, @output_module])
        assert :ok = run([@input, @output, @output_module])
      end)

    assert output =~ "Generated #{@output_module}"
    assert File.exists?(@output)
  end

  defp formatted(source) do
    source
    |> Code.format_string!()
    |> IO.iodata_to_binary()
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end
end
