defmodule XMAVLink.Test.Tasks do
  use ExUnit.Case

  import ExUnit.CaptureIO
  import Mix.Tasks.Xmavlink

  @input "#{File.cwd!()}/test/input/test_mavlink.xml"
  @extensions_input "#{File.cwd!()}/test/input/test_extensions.xml"
  @extension_defaults_input "#{File.cwd!()}/test/input/test_extension_defaults.xml"
  @output_dir "#{Mix.Project.build_path()}/generated"
  @output "#{@output_dir}/test_mavlink.ex"
  @output_module "TestMavlink"

  setup do
    File.rm_rf!(@output_dir)
    File.mkdir_p!(@output_dir)

    :ok
  end

  test "generate" do
    output =
      capture_io(fn ->
        assert :ok = run([@input, @output, @output_module])
      end)

    assert output =~ "Generated #{@output_module}"
    assert File.exists?(@output)

    # Confirm the list of modules generated from common.xml and its includes
    pairs =
      with_module_conflict_ignored(fn ->
        Enum.zip(
          [
            XMAVLink.Message.TestMavlink.Message.ChangeOperatorControl,
            XMAVLink.Message.TestMavlink.Message.Data16,
            XMAVLink.Message.TestMavlink.Message.Heartbeat,
            XMAVLink.Message.TestMavlink.Message.VfrHud,
            TestMavlink,
            TestMavlink.Message.ChangeOperatorControl,
            TestMavlink.Message.Data16,
            TestMavlink.Message.Heartbeat,
            TestMavlink.Message.VfrHud,
            TestMavlink.Types
          ]
          |> Enum.sort(),
          Code.compile_file(@output)
          |> Keyword.keys()
          |> Enum.sort()
        )
      end)

    for {expected, actual} <- pairs do
      assert expected == actual
    end
  end

  test "generated output is deterministic and formatter-compatible" do
    output_a = Path.join(@output_dir, "deterministic_a.ex")
    output_b = Path.join(@output_dir, "deterministic_b.ex")

    capture_io(fn ->
      assert :ok = run([@input, output_a, @output_module])
      assert :ok = run([@input, output_b, @output_module])
    end)

    generated = File.read!(output_a)

    assert generated == File.read!(output_b)
    assert generated == formatted(generated)
    refute generated =~ @input
    assert generated =~ "generated by MAVLink mix task from test_mavlink.xml"
  end

  test "generate succeeds when output is already current" do
    output =
      capture_io(fn ->
        assert :ok = run([@input, @output, @output_module])
        assert :ok = run([@input, @output, @output_module])
      end)

    assert output =~ "Generated #{@output_module}"
    assert File.exists?(@output)
  end

  test "invalid module name raises a clear generator error" do
    assert_raise Mix.Error, ~r/Invalid module name "bad.Module"/, fn ->
      run([@input, @output, "bad.Module"])
    end
  end

  test "parser validation errors raise clear generator errors" do
    input =
      write_xml("invalid_identifier.xml", """
      <?xml version="1.0"?>
      <mavlink>
        <version>3</version>
        <dialect>0</dialect>
        <messages>
          <message id="1" name="TEST_MESSAGE">
            <field type="uint8_t" name="bad-name">Value</field>
          </message>
        </messages>
      </mavlink>
      """)

    assert_raise Mix.Error, ~r/Invalid field name "bad-name"/, fn ->
      run([input, @output, @output_module])
    end
  end

  test "generated docs and descriptions are escaped without interpolation" do
    input =
      write_xml("escaped_docs.xml", ~S"""
      <?xml version="1.0"?>
      <mavlink>
        <version>3</version>
        <dialect>0</dialect>
        <enums>
          <enum name="TEST_ENUM">
            <description>Enum "quoted" #{raise "boom"}</description>
            <entry value="0" name="TEST_ENTRY">
              <description>Entry #{raise "boom"}</description>
              <param index="1">Param #{raise "boom"}</param>
            </entry>
          </enum>
        </enums>
        <messages>
          <message id="1" name="TEST_MESSAGE">
            <description>Message #{raise "boom"}</description>
            <field type="char[4]" name="label">Field #{raise "boom"}</field>
            <field type="uint8_t[2]" name="values">Array #{raise "boom"}</field>
            <field type="float" name="ratio">Ratio #{raise "boom"}</field>
          </message>
        </messages>
      </mavlink>
      """)

    output = Path.join(@output_dir, "escaped_docs.ex")

    capture_io(fn ->
      assert :ok = run([input, output, "EscapedDocs"])
    end)

    with_module_conflict_ignored(fn -> Code.compile_file(output) end)

    assert apply(EscapedDocs, :describe, [:test_enum]) == ~S(Enum "quoted" #{raise "boom"})
    assert apply(EscapedDocs, :describe, [:test_entry]) == ~S(Entry #{raise "boom"})
    assert apply(EscapedDocs, :describe_params, [:test_entry]) == [{1, ~S(Param #{raise "boom"})}]
  end

  test "generated MAVLink 2 unpack ignores future extension bytes" do
    output = Path.join(@output_dir, "test_extensions.ex")

    capture_io(fn ->
      assert :ok = run([@extensions_input, output, "TestExtensions"])
    end)

    with_module_conflict_ignored(fn -> Code.compile_file(output) end)

    payload =
      XMAVLink.Utils.pack_float(12.5) <>
        <<200>> <> XMAVLink.Utils.pack_float(1.25) <> XMAVLink.Utils.pack_float(-2.5) <> <<9, 8>>

    {:ok, crc_extra, _expected_length, _target} = apply(TestExtensions, :msg_attributes, [100])
    assert {:ok, frame} = frame_from_mavlink_2_packet(100, payload, crc_extra)
    assert {:ok, %{message: message}} = XMAVLink.Frame.validate_and_unpack(frame, TestExtensions)

    assert message.quality == 200
    assert_in_delta message.ground_distance, 12.5, 0.0001
    assert_in_delta message.flow_rate_x, 1.25, 0.0001
    assert_in_delta message.flow_rate_y, -2.5, 0.0001
  end

  test "generated MAVLink 2 unpack ignores future extension bytes for messages without known extensions" do
    output = Path.join(@output_dir, "test_no_known_extensions.ex")

    capture_io(fn ->
      assert :ok = run([@input, output, "TestNoKnownExtensions"])
    end)

    with_module_conflict_ignored(fn -> Code.compile_file(output) end)

    assert {:ok, message} = apply(TestNoKnownExtensions, :unpack, [0, 2, <<0, 9, 8, 7>>])
    assert message.type == :mav_type_generic
  end

  test "generated MAVLink 2 pack defaults omitted extension fields to zero-equivalent values" do
    output = Path.join(@output_dir, "test_extension_defaults.ex")

    capture_io(fn ->
      assert :ok = run([@extension_defaults_input, output, "TestExtensionDefaults"])
    end)

    with_module_conflict_ignored(fn -> Code.compile_file(output) end)

    message = struct(TestExtensionDefaults.Message.ExtensionDefaults, base_value: 9)

    assert {:ok, 200, {:ok, _crc_extra, _expected_size, :broadcast}, <<9>>} =
             XMAVLink.Message.pack(message, 1)

    expected_mavlink_2_payload =
      <<9, 0::little-unsigned-integer-size(16), 0.0::little-float-size(32),
        0.0::little-float-size(64), 0::size(32), 0::little-unsigned-integer-size(16),
        0::little-unsigned-integer-size(16), 0::little-unsigned-integer-size(16),
        0.0::little-float-size(32), 0.0::little-float-size(32), 0.0::little-float-size(64),
        0.0::little-float-size(64), 0, 0>>

    assert {:ok, 200, {:ok, _crc_extra, _expected_size, :broadcast}, ^expected_mavlink_2_payload} =
             XMAVLink.Message.pack(message, 2)
  end

  test "generated MAVLink 2 pack preserves provided extension field values" do
    output = Path.join(@output_dir, "test_extension_values.ex")

    capture_io(fn ->
      assert :ok = run([@extension_defaults_input, output, "TestExtensionValues"])
    end)

    with_module_conflict_ignored(fn -> Code.compile_file(output) end)

    message =
      struct(TestExtensionValues.Message.ExtensionDefaults,
        base_value: 9,
        scalar_value: 513,
        float_value: 1.25,
        double_value: 2.5,
        label: "AB",
        counts: [1, 2, 3],
        ratios: [4.5, 5.5],
        precisions: [6.5, 7.5],
        mode: :test_mode_active,
        flags: MapSet.new([:test_flag_one, :test_flag_two])
      )

    expected_mavlink_2_payload =
      <<9, 513::little-unsigned-integer-size(16), 1.25::little-float-size(32),
        2.5::little-float-size(64), "AB", 0, 0, 1::little-unsigned-integer-size(16),
        2::little-unsigned-integer-size(16), 3::little-unsigned-integer-size(16),
        4.5::little-float-size(32), 5.5::little-float-size(32), 6.5::little-float-size(64),
        7.5::little-float-size(64), 1, 3>>

    assert {:ok, 200, {:ok, _crc_extra, _expected_size, :broadcast}, ^expected_mavlink_2_payload} =
             XMAVLink.Message.pack(message, 2)

    assert {:ok, decoded} =
             apply(TestExtensionValues, :unpack, [200, 2, expected_mavlink_2_payload])

    assert decoded.ratios == [4.5, 5.5]
    assert decoded.precisions == [6.5, 7.5]

    assert {:ok, 200, {:ok, _crc_extra, _expected_size, :broadcast}, ^expected_mavlink_2_payload} =
             XMAVLink.Message.pack(decoded, 2)
  end

  defp formatted(source) do
    source
    |> Code.format_string!()
    |> IO.iodata_to_binary()
    |> String.trim_trailing()
    |> Kernel.<>("\n")
  end

  defp write_xml(name, contents) do
    path = Path.join(@output_dir, name)
    File.write!(path, contents)
    path
  end

  defp with_module_conflict_ignored(fun) do
    previous_compiler_options = Code.compiler_options()
    Code.compiler_options(ignore_module_conflict: true)

    try do
      fun.()
    after
      Code.compiler_options(previous_compiler_options)
    end
  end

  defp frame_from_mavlink_2_packet(message_id, payload, crc_extra) do
    mavlink_2_frame =
      <<byte_size(payload), 0, 0, 7, 1, 1, message_id::little-unsigned-integer-size(24),
        payload::binary>>

    checksum =
      mavlink_2_frame
      |> XMAVLink.Utils.x25_crc()
      |> XMAVLink.Utils.x25_crc([crc_extra])

    case XMAVLink.Frame.binary_to_frame_and_tail(
           <<0xFD>> <> mavlink_2_frame <> <<checksum::little-unsigned-integer-size(16)>>
         ) do
      {frame, <<>>} -> {:ok, frame}
      other -> other
    end
  end
end
